name = "Jinyang Yao"
downloads-dir = "~/.mail"
signature = """
--
Best,
"""

[hotmail]
default = true
email = "jimmy123good@hotmail.com"

imap-host = "imap-mail.outlook.com"
imap-port = 993
imap-login = "jimmy123good@hotmail.com"
imap-passwd-cmd = "pass show jimmy123good@hotmail.com"

smtp-host = "smtp-mail.outlook.com"
smtp-port = 587
smtp-login = "jimmy123good@hotmail.com"
smtp-passwd-cmd = "pass show jimmy123good@hotmail.com"
